'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Camera, CircleAlert, ClipboardCheck, HelpCircle, ImagePlus, LayoutDashboard, LogOut, Menu, Pencil, Plus, Trash2, Users, X } from 'lucide-react';
import { RegistrationProgress, RegistrationReview, SquadProgress, StatusBadge } from './components';
import BrandLink from '../components/BrandLink';
import DashboardBrand from '../components/DashboardBrand';

type Player = { id:string; first_name:string; last_name:string; date_of_birth:string; jersey_number:number; position:string; height_cm:number; preferred_foot:string; status:string; rejection_reason?:string|null; photo_url:string };
type InitialData = { department:{name:string}; team:{status:string;final_submitted:boolean;rejection_reason?:string|null}; players:Player[]; logoUrl:string|null };
type FieldErrors = Record<string,string>;
const MAX_FILE_SIZE = 5*1024*1024;

function validatePhoto(file?:File, required=true) { if(!file||file.size===0)return required?'Player photo is required.':''; if(!['image/jpeg','image/jpg'].includes(file.type))return 'Player photo must be a JPEG image.'; if(file.size>MAX_FILE_SIZE)return 'Maximum photo size is 5 MB.'; return ''; }
function validateForm(form:HTMLFormElement, players:Player[], editingId?:string) { const data=new FormData(form); const errors:FieldErrors={}; for(const field of ['first_name','last_name','date_of_birth','jersey_number','position','height_cm','preferred_foot']) if(!String(data.get(field)||'').trim()) errors[field]=field==='date_of_birth'?'Date of birth is required.':field==='position'?'Please select a playing position.':'This field is required.'; const jersey=Number(data.get('jersey_number')); if(jersey&&players.some(p=>p.id!==editingId&&p.jersey_number===jersey))errors.jersey_number='This jersey number is already assigned to another player.'; const photo=data.get('photo'); const photoError=validatePhoto(photo instanceof File?photo:undefined,!editingId); if(photoError)errors.photo=photoError; return errors; }
function FieldError({name,errors}:{name:string;errors:FieldErrors}) { return errors[name]?<span className="field-error" role="alert">{errors[name]}</span>:null; }

export default function DashboardClient({initial}:{initial:InitialData}) {
  const router=useRouter(); const [notice,setNotice]=useState<{type:'error'|'success';text:string}|null>(null); const [busyAction,setBusyAction]=useState(''); const [editing,setEditing]=useState<Player|null>(null); const [errors,setErrors]=useState<FieldErrors>({}); const [photoPreview,setPhotoPreview]=useState(''); const [editPhotoPreview,setEditPhotoPreview]=useState(''); const [navigationOpen,setNavigationOpen]=useState(false); const [activeSection,setActiveSection]=useState<'dashboard'|'team'|'add'|'players'|'review'>('dashboard'); const logoInput=useRef<HTMLInputElement>(null);
 const players=initial.players||[]; const locked=!!initial.team?.final_submitted; const allApproved=players.length>0&&players.every(p=>p.status==='approved'); const registrationStatus=initial.team?.status==='rejected'?'rejected':initial.team?.status==='approved'&&allApproved?'approved':'pending';
 useEffect(()=>{if(notice?.type!=='success')return;const timer=window.setTimeout(()=>setNotice(null),5000);return()=>window.clearTimeout(timer);},[notice]);
 useEffect(()=>{if(activeSection!=='review')return;const frame=window.requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));return()=>window.cancelAnimationFrame(frame);},[activeSection]);
 function showPreview(file:File|undefined,setter:(v:string)=>void,required=true){const error=validatePhoto(file,required);setErrors(e=>({...e,photo:error}));if(error||!file){setter('');return;}setter(URL.createObjectURL(file));}
 async function request(path:string,options:RequestInit,action:string){setBusyAction(action);setNotice(null);try{const response=await fetch(path,options);const result=await response.json().catch(()=>({}));if(!response.ok){setNotice({type:'error',text:result.error||'The request could not be completed. Please try again.'});return false;}router.refresh();return true;}catch{setNotice({type:'error',text:'Unable to connect. Check your internet connection and try again.'});return false;}finally{setBusyAction('');}}
 async function updateTeamLogo(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.type!=='image/png'||file.size>MAX_FILE_SIZE){setNotice({type:'error',text:file.type!=='image/png'?'Team logo must be a PNG image.':'Maximum logo size is 5 MB.'});e.target.value='';return;}const form=new FormData();form.set('logo',file);if(await request('/api/team',{method:'POST',body:form},'logo'))setNotice({type:'success',text:'Team logo updated successfully.'});e.target.value='';}
 async function addPlayer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const next=validateForm(form,players);setErrors(next);if(Object.keys(next).length){setNotice({type:'error',text:'Please correct the highlighted fields.'});return;}if(await request('/api/players',{method:'POST',body:new FormData(form)},'add')){form.reset();setPhotoPreview('');setErrors({});const count=players.length+1;setNotice({type:'success',text:`Player saved successfully — ${Math.min(count,20)} of 20 minimum completed.`});}}
 async function removePlayer(id:string){if(!confirm('Remove this player from the squad? This cannot be undone.'))return;if(await request('/api/players',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})},`remove-${id}`))setNotice({type:'success',text:'Player removed successfully.'});}
 async function editPlayer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const form=e.currentTarget;const next=validateForm(form,players,editing.id);setErrors(next);if(Object.keys(next).length)return;if(await request('/api/players',{method:'PATCH',body:new FormData(form)},'edit')){setEditing(null);setEditPhotoPreview('');setErrors({});setNotice({type:'success',text:'Player changes saved successfully.'});}}
 async function submitRegistration(){if(!confirm('Submit this squad for admin review? Player and team editing will be locked.'))return;if(await request('/api/submit',{method:'POST'},'submit'))setNotice({type:'success',text:'Registration submitted successfully.'});}
 async function logout(){if(!confirm('Are you sure you want to log out?'))return;await request('/api/logout',{method:'POST'},'logout');router.push('/');router.refresh();}

 const playerFields=(p?:Player)=><>
  <div className="form-field"><label htmlFor={p?'edit-first':'player-first'}>First name</label><input id={p?'edit-first':'player-first'} name="first_name" className="input" defaultValue={p?.first_name} aria-invalid={!!errors.first_name} required/><FieldError name="first_name" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-last':'player-last'}>Last name</label><input id={p?'edit-last':'player-last'} name="last_name" className="input" defaultValue={p?.last_name} aria-invalid={!!errors.last_name} required/><FieldError name="last_name" errors={errors}/></div>
  <div className="form-field"><label>Nationality</label><input className="input" value="Nigeria" readOnly/></div>
  <div className="form-field"><label htmlFor={p?'edit-dob':'player-dob'}>Date of birth</label><input id={p?'edit-dob':'player-dob'} name="date_of_birth" className="input" type="date" defaultValue={p?.date_of_birth} aria-invalid={!!errors.date_of_birth} required/><FieldError name="date_of_birth" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-jersey':'player-jersey'}>Jersey number</label><input id={p?'edit-jersey':'player-jersey'} name="jersey_number" className="input" type="number" min="1" max="99" defaultValue={p?.jersey_number} aria-invalid={!!errors.jersey_number} required/><FieldError name="jersey_number" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-position':'player-position'}>Position</label><select id={p?'edit-position':'player-position'} name="position" className="select" defaultValue={p?.position||''} aria-invalid={!!errors.position} required><option value="" disabled>Select position</option><option>Goalkeeper</option><option>Defender</option><option>Midfielder</option><option>Forward</option></select><FieldError name="position" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-height':'player-height'}>Height (cm)</label><input id={p?'edit-height':'player-height'} name="height_cm" className="input" type="number" min="140" max="240" defaultValue={p?.height_cm} aria-invalid={!!errors.height_cm} required/><FieldError name="height_cm" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-foot':'player-foot'}>Preferred foot</label><select id={p?'edit-foot':'player-foot'} name="preferred_foot" className="select" defaultValue={p?.preferred_foot||''} aria-invalid={!!errors.preferred_foot} required><option value="" disabled>Select preferred foot</option><option>Right</option><option>Left</option></select><FieldError name="preferred_foot" errors={errors}/></div>
 </>;

 const approvedCount=players.filter(player=>player.status==='approved').length;
 const pendingCount=players.filter(player=>player.status==='pending').length;
 const rejectedCount=players.filter(player=>player.status==='rejected').length;
 return <main className={`department-shell section-${activeSection}`}>
  <header className="app-topbar"><div className="topbar-brand-group"><button className="dashboard-menu-button" type="button" onClick={()=>setNavigationOpen(true)} aria-label="Open dashboard navigation" aria-expanded={navigationOpen}><Menu size={19}/></button><BrandLink /></div><div className="topbar-department">{initial.logoUrl?<img className="topbar-department-logo" src={initial.logoUrl} alt={`${initial.department.name} logo`}/>:<span>{initial.department.name.slice(0,2).toUpperCase()}</span>}<b>{initial.department.name}</b><button type="button" onClick={logout} disabled={!!busyAction} aria-label="Log out"><LogOut size={17}/></button></div></header>
  <div className="dashboard-frame">
    {navigationOpen&&<button className="dashboard-nav-backdrop" type="button" onClick={()=>setNavigationOpen(false)} aria-label="Close dashboard navigation"/>}<aside className={`dashboard-sidebar${navigationOpen?' open':''}`} aria-label="Registration navigation"><button className="dashboard-nav-close" type="button" onClick={()=>setNavigationOpen(false)} aria-label="Close navigation"><X/></button><DashboardBrand/><nav><button className={activeSection==='dashboard'?'active':''} type="button" onClick={()=>{setActiveSection('dashboard');setNavigationOpen(false)}}><LayoutDashboard/> Dashboard</button><button className={activeSection==='add'?'active':''} type="button" onClick={()=>{setActiveSection('add');setNavigationOpen(false)}}><Plus/> Add Player</button><button className={activeSection==='players'?'active':''} type="button" onClick={()=>{setActiveSection('players');setNavigationOpen(false)}}><Users/> Players</button><button className={activeSection==='review'?'active':''} type="button" onClick={()=>{setActiveSection('review');setNavigationOpen(false)}}><ClipboardCheck/> Review & Submit</button></nav><div><a href="mailto:support@afit.edu.ng"><HelpCircle/> Help & Support</a><button type="button" onClick={logout} disabled={!!busyAction}><LogOut/> Logout</button></div></aside>
   <div className="department-page" id="dashboard-overview">
  {activeSection!=='dashboard'&&activeSection!=='review'&&<button className="section-back-button" type="button" onClick={()=>setActiveSection('dashboard')}><ArrowLeft/> <span>Back to Dashboard</span></button>}
  {(activeSection==='dashboard'||activeSection==='team')&&<header className="department-header"><div className="welcome-block"><div><span>{activeSection==='dashboard'?'Welcome Back':'Team Registration'}</span><h1>{initial.department.name}</h1><StatusBadge value={registrationStatus}/><p>{activeSection==='dashboard'?'Complete your squad registration and submit before the deadline.':'Review or update your registered department logo.'}</p></div><div className="team-identity-card"><button className="department-logo-button" type="button" onClick={()=>!locked&&logoInput.current?.click()} disabled={locked||!!busyAction} aria-label={locked?'Team logo editing is locked':'Replace team logo'}>{initial.logoUrl?<img src={initial.logoUrl} alt={`${initial.department.name} logo`}/>:<ImagePlus/>}{!locked&&<span><Camera size={13}/> Change</span>}</button><input ref={logoInput} className="visually-hidden" type="file" accept="image/png" onChange={updateTeamLogo}/><div><b>{initial.department.name}</b></div></div></div></header>}
  {initial.team.rejection_reason&&<div className="notice notice-error"><CircleAlert size={18}/><span><b>Team review:</b> {initial.team.rejection_reason}</span></div>}
  {notice&&<div className={`notice notice-${notice.type}`} role={notice.type==='error'?'alert':'status'}><span>{notice.text}</span><button type="button" onClick={()=>setNotice(null)} aria-label="Dismiss message"><X size={16}/></button></div>}
   {activeSection==='dashboard'&&<><RegistrationProgress playerCount={players.length} submitted={locked}/><div className="dashboard-overview-grid"><SquadProgress count={players.length} approved={approvedCount} pending={pendingCount} rejected={rejectedCount}/><section className="registration-status-card" aria-labelledby="registration-status-title"><h2 id="registration-status-title">Registration Status</h2><dl><div><dt>Players Registered</dt><dd>{players.length}</dd></div><div><dt>Approved Players</dt><dd className="approved-value">{approvedCount}</dd></div><div><dt>Pending Approval</dt><dd className="pending-value">{pendingCount}</dd></div><div><dt>Rejected Players</dt><dd className="rejected-value">{rejectedCount}</dd></div><div><dt>Minimum Required</dt><dd>20</dd></div><div><dt>Maximum Allowed</dt><dd>25</dd></div><div><dt>Status</dt><dd><StatusBadge value={registrationStatus}/></dd></div></dl><p>{locked?'Registration submitted for review.':approvedCount<20?<>You need <b>{20-approvedCount} more approved players</b> to meet the minimum requirement.</>:'Your approved squad meets the minimum requirement and is ready for review.'}</p></section></div><div className="dashboard-primary-actions"><button className="btn primary-action" type="button" onClick={()=>setActiveSection('add')}><Plus size={17}/> Add player</button><button className="btn secondary" type="button" onClick={()=>setActiveSection('players')}><Users size={17}/> View players</button><button className="btn review-action" type="button" onClick={()=>setActiveSection('review')}><ClipboardCheck size={17}/> Review & Submit</button></div></>}
   {(activeSection==='add'||activeSection==='players')&&<div className={`department-workspace single-workspace ${activeSection}`} id="players">
    <section className="card add-player-card" id="add-player"><div className="section-title"><div><h2>Add player</h2></div><span>{players.length}/25</span></div>
    {locked?<div className="review-notice">Registration is submitted and editing is locked.</div>:players.length>=25?<div className="review-notice success-notice">Maximum squad size reached.</div>:<form className="player-form" onSubmit={addPlayer} noValidate>
     <div className="photo-upload-field"><label className={`photo-picker ${errors.photo?'has-error':''}`}>{photoPreview?<img src={photoPreview} alt="Selected player preview"/>:<><Camera size={34}/><b>Choose photo</b></>}<input name="photo" type="file" accept="image/jpeg,.jpg,.jpeg" onChange={e=>showPreview(e.target.files?.[0],setPhotoPreview)} required/></label><div><b>Player photo</b><p>JPEG only · Maximum 5 MB</p><p>Keep face centered, clear background.</p>{photoPreview&&<span className="replace-hint">Tap the preview to replace image</span>}<FieldError name="photo" errors={errors}/></div></div>
     <div className="player-form-grid">{playerFields()}</div><button className="btn primary-action full" disabled={!!busyAction}><Plus size={17}/>{busyAction==='add'?'Saving player...':'Save player'}</button>
    </form>}
   </section>
   <section className="card player-list-card"><div className="section-title"><div><div className="kicker">Squad list</div><h2>Registered players</h2></div><b>{players.length}</b></div><div className="player-card-list">{players.length===0?<div className="empty-player-list"><Camera size={28}/><b>No players registered yet</b><span>Add the first player to begin building your squad.</span></div>:players.map(p=><article className="player-card" key={p.id}><img src={p.photo_url} alt={`${p.first_name} ${p.last_name}`}/><div className="player-card-info"><h3><span>{String(p.jersey_number).padStart(2,'0')}</span>{p.first_name} {p.last_name}</h3><p>{p.position} · {p.preferred_foot} foot</p><StatusBadge value={p.status}/>{p.rejection_reason&&<div className="player-reason"><CircleAlert size={14}/> {p.rejection_reason}</div>}</div>{!locked&&p.status!=='approved'&&<div className="player-actions"><button className="btn secondary tiny" type="button" onClick={()=>{setErrors({});setEditing(p);}}><Pencil size={14}/> Edit</button><button className="btn danger tiny" type="button" onClick={()=>removePlayer(p.id)} disabled={busyAction===`remove-${p.id}`}><Trash2 size={14}/> {busyAction===`remove-${p.id}`?'Removing...':'Remove'}</button></div>}</article>)}</div></section>
  </div>}
  {activeSection==='review'&&<RegistrationReview department={initial.department.name} logoUrl={initial.logoUrl} players={players} submitted={locked} onSubmit={submitRegistration} onBack={()=>setActiveSection('dashboard')} onChangeLogo={()=>setActiveSection('team')} busy={busyAction==='submit'}/>} 
   {!locked&&players.length<25&&activeSection==='players'&&<button className="mobile-add-player" type="button" onClick={()=>setActiveSection('add')}><Plus size={19}/> Add player</button>}
  {editing&&<div className="edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><form className="card edit-player-card" onSubmit={editPlayer} noValidate><div className="section-title"><div><div className="kicker">Update squad member</div><h2 id="edit-title">Edit player</h2></div><button type="button" className="icon-button" onClick={()=>setEditing(null)} aria-label="Close"><X size={20}/></button></div><input type="hidden" name="id" value={editing.id}/><div className="edit-photo-row"><img src={editPhotoPreview||editing.photo_url} alt={`${editing.first_name} ${editing.last_name}`}/><label className="btn secondary">Replace image<input name="photo" type="file" accept="image/jpeg,.jpg,.jpeg" onChange={e=>showPreview(e.target.files?.[0],setEditPhotoPreview,false)}/></label><span>JPEG only · Maximum 5 MB</span><FieldError name="photo" errors={errors}/></div><div className="player-form-grid">{playerFields(editing)}</div>{notice?.type==='error'&&<div className="notice notice-error">{notice.text}</div>}<div className="edit-actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn" disabled={!!busyAction}>{busyAction==='edit'?'Saving changes...':'Save changes'}</button></div></form></div>}
   </div>
  </div>
 </main>;
}
