'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Camera, CircleAlert, ClipboardCheck, ImagePlus, LayoutDashboard, Pencil, Plus, Search, ShieldCheck, SlidersHorizontal, Trash2, Users, X } from 'lucide-react';
import { RegistrationReview, StatusBadge } from './components';
import BrandLink from '../components/BrandLink';

type Player = { id:string; first_name:string; last_name:string; date_of_birth:string; jersey_number:number; position:string; height_cm:number; preferred_foot:string; status:string; rejection_reason?:string|null; photo_url:string };
type InitialData = { department:{name:string}; team:{status:string;final_submitted:boolean;rejection_reason?:string|null}; players:Player[]; logoUrl:string|null };
type FieldErrors = Record<string,string>;
const MAX_FILE_SIZE = 5*1024*1024;

function validatePhoto(file?:File, required=true) { if(!file||file.size===0)return required?'Player photo is required.':''; if(!['image/jpeg','image/jpg'].includes(file.type))return 'Player photo must be a JPEG image.'; if(file.size>MAX_FILE_SIZE)return 'Maximum photo size is 5 MB.'; return ''; }
function validateForm(form:HTMLFormElement, players:Player[], editingId?:string) { const data=new FormData(form); const errors:FieldErrors={}; for(const field of ['first_name','last_name','date_of_birth','jersey_number','position','height_cm','preferred_foot']) if(!String(data.get(field)||'').trim()) errors[field]=field==='date_of_birth'?'Date of birth is required.':field==='position'?'Please select a playing position.':'This field is required.'; const jersey=Number(data.get('jersey_number')); if(jersey&&players.some(p=>p.id!==editingId&&p.jersey_number===jersey))errors.jersey_number='This jersey number is already assigned to another player.'; const photo=data.get('photo'); const photoError=validatePhoto(photo instanceof File?photo:undefined,!editingId); if(photoError)errors.photo=photoError; return errors; }
function FieldError({name,errors}:{name:string;errors:FieldErrors}) { return errors[name]?<span className="field-error" role="alert">{errors[name]}</span>:null; }

export default function DashboardClient({initial}:{initial:InitialData}) {
  const router=useRouter(); const [notice,setNotice]=useState<{type:'error'|'success';text:string}|null>(null); const [busyAction,setBusyAction]=useState(''); const [editing,setEditing]=useState<Player|null>(null); const [errors,setErrors]=useState<FieldErrors>({}); const [photoPreview,setPhotoPreview]=useState(''); const [editPhotoPreview,setEditPhotoPreview]=useState(''); const [playerQuery,setPlayerQuery]=useState(''); const [showSubmissionModal,setShowSubmissionModal]=useState(false); const [activeSection,setActiveSection]=useState<'dashboard'|'team'|'add'|'players'|'review'>('dashboard'); const logoInput=useRef<HTMLInputElement>(null);
 const players=initial.players||[]; const locked=!!initial.team?.final_submitted; const allApproved=players.length>0&&players.every(p=>p.status==='approved'); const registrationStatus=initial.team?.status==='rejected'?'rejected':initial.team?.status==='approved'&&allApproved?'approved':'pending';
 useEffect(()=>{if(notice?.type!=='success')return;const timer=window.setTimeout(()=>setNotice(null),5000);return()=>window.clearTimeout(timer);},[notice]);
 useEffect(()=>{if(activeSection!=='review')return;const frame=window.requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'auto'}));return()=>window.cancelAnimationFrame(frame);},[activeSection]);
 function showPreview(file:File|undefined,setter:(v:string)=>void,required=true){const error=validatePhoto(file,required);setErrors(e=>({...e,photo:error}));if(error||!file){setter('');return;}setter(URL.createObjectURL(file));}
 async function request(path:string,options:RequestInit,action:string){setBusyAction(action);setNotice(null);try{const response=await fetch(path,options);const result=await response.json().catch(()=>({}));if(!response.ok){setNotice({type:'error',text:result.error||'The request could not be completed. Please try again.'});return false;}router.refresh();return true;}catch{setNotice({type:'error',text:'Unable to connect. Check your internet connection and try again.'});return false;}finally{setBusyAction('');}}
 async function updateTeamLogo(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.type!=='image/png'||file.size>MAX_FILE_SIZE){setNotice({type:'error',text:file.type!=='image/png'?'Team logo must be a PNG image.':'Maximum logo size is 5 MB.'});e.target.value='';return;}const form=new FormData();form.set('logo',file);if(await request('/api/team',{method:'POST',body:form},'logo'))setNotice({type:'success',text:'Team logo updated successfully.'});e.target.value='';}
 async function addPlayer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const next=validateForm(form,players);setErrors(next);if(Object.keys(next).length){setNotice({type:'error',text:'Please correct the highlighted fields.'});return;}if(await request('/api/players',{method:'POST',body:new FormData(form)},'add')){form.reset();setPhotoPreview('');setErrors({});const count=players.length+1;setNotice({type:'success',text:`Player saved successfully — ${Math.min(count,20)} of 20 minimum completed.`});}}
 async function removePlayer(id:string){if(!confirm('Remove this player from the squad? This cannot be undone.'))return;if(await request('/api/players',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})},`remove-${id}`))setNotice({type:'success',text:'Player removed successfully.'});}
 async function editPlayer(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const form=e.currentTarget;const next=validateForm(form,players,editing.id);setErrors(next);if(Object.keys(next).length)return;if(await request('/api/players',{method:'PATCH',body:new FormData(form)},'edit')){setEditing(null);setEditPhotoPreview('');setErrors({});setNotice({type:'success',text:'Player changes saved successfully.'});}}
 async function submitRegistration(){if(!confirm('Submit this squad for admin review? Player and team editing will be locked.'))return;if(await request('/api/submit',{method:'POST'},'submit')){setNotice(null);setShowSubmissionModal(true);}}
 async function logout(){if(!confirm('Are you sure you want to log out?'))return;await request('/api/logout',{method:'POST'},'logout');router.push('/');router.refresh();}

 const playerFields=(p?:Player)=><>
  <div className="form-field"><label htmlFor={p?'edit-first':'player-first'}>First name</label><input id={p?'edit-first':'player-first'} name="first_name" className="input" defaultValue={p?.first_name} aria-invalid={!!errors.first_name} required/><FieldError name="first_name" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-last':'player-last'}>Last name</label><input id={p?'edit-last':'player-last'} name="last_name" className="input" defaultValue={p?.last_name} aria-invalid={!!errors.last_name} required/><FieldError name="last_name" errors={errors}/></div>
  <div className="form-field"><label>Nationality</label><input className="input" value="Nigeria" readOnly/></div>
  <div className="form-field"><label htmlFor={p?'edit-dob':'player-dob'}>Date of birth</label><input id={p?'edit-dob':'player-dob'} name="date_of_birth" className="input date-picker-input" type="date" defaultValue={p?.date_of_birth} aria-invalid={!!errors.date_of_birth} onClick={(event)=>event.currentTarget.showPicker?.()} required/><FieldError name="date_of_birth" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-jersey':'player-jersey'}>Jersey number</label><input id={p?'edit-jersey':'player-jersey'} name="jersey_number" className="input" type="number" min="1" max="99" defaultValue={p?.jersey_number} aria-invalid={!!errors.jersey_number} required/><FieldError name="jersey_number" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-position':'player-position'}>Position</label><select id={p?'edit-position':'player-position'} name="position" className="select" defaultValue={p?.position||''} aria-invalid={!!errors.position} required><option value="" disabled>Select position</option><option>Goalkeeper</option><option>Defender</option><option>Midfielder</option><option>Forward</option></select><FieldError name="position" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-height':'player-height'}>Height (cm)</label><input id={p?'edit-height':'player-height'} name="height_cm" className="input" type="number" min="140" max="240" defaultValue={p?.height_cm} aria-invalid={!!errors.height_cm} required/><FieldError name="height_cm" errors={errors}/></div>
  <div className="form-field"><label htmlFor={p?'edit-foot':'player-foot'}>Preferred foot</label><select id={p?'edit-foot':'player-foot'} name="preferred_foot" className="select" defaultValue={p?.preferred_foot||''} aria-invalid={!!errors.preferred_foot} required><option value="" disabled>Select preferred foot</option><option>Right</option><option>Left</option></select><FieldError name="preferred_foot" errors={errors}/></div>
 </>;

 const approvedCount=players.filter(player=>player.status==='approved').length;
 const pendingCount=players.filter(player=>player.status==='pending').length;
 const rejectedCount=players.filter(player=>player.status==='rejected').length;
 const positionSummary=[
  {label:'Goalkeepers',count:players.filter(player=>player.position==='Goalkeeper').length,color:'#174ea6'},
  {label:'Defenders',count:players.filter(player=>player.position==='Defender').length,color:'#0876c9'},
  {label:'Midfielders',count:players.filter(player=>player.position==='Midfielder').length,color:'#20a64a'},
  {label:'Attackers',count:players.filter(player=>player.position==='Forward').length,color:'#db202b'},
 ];
 let positionCursor=0;
 const positionSegments=positionSummary.map(item=>{const start=positionCursor;positionCursor+=players.length?item.count/players.length*100:0;return `${item.color} ${start}% ${positionCursor}%`;});
 if(!players.length)positionSegments.push('#e9eef2 0% 100%');
 const registrationPercent=Math.min(100,Math.round(players.length/25*100));
 const visiblePlayers=players.filter(player=>`${player.first_name} ${player.last_name} ${player.position} ${player.jersey_number}`.toLowerCase().includes(playerQuery.trim().toLowerCase()));
 return <main className={`department-shell section-${activeSection}`}>
  <header className="app-topbar"><div className="topbar-brand-group"><BrandLink /></div><div className="topbar-department"><button className="dashboard-logout-text" type="button" onClick={logout} disabled={!!busyAction}>Logout</button></div></header>
  <div className="dashboard-frame">
    <footer className="dashboard-footer-nav" aria-label="Registration navigation"><nav><button className={activeSection==='dashboard'?'active':''} type="button" onClick={()=>setActiveSection('dashboard')}><LayoutDashboard/> <span>Dashboard</span></button><button className={activeSection==='add'?'active':''} type="button" onClick={()=>setActiveSection('add')}><Plus/> <span>Add Player</span></button><button className={activeSection==='players'?'active':''} type="button" onClick={()=>setActiveSection('players')}><Users/> <span>Players</span></button><button className={activeSection==='review'?'active':''} type="button" onClick={()=>setActiveSection('review')}><ClipboardCheck/> <span>Review &amp; Submit</span></button></nav></footer>
   <div className="department-page" id="dashboard-overview">
  {(activeSection==='dashboard'||activeSection==='team')&&<header className="department-header"><div className="welcome-block"><div><span>{activeSection==='dashboard'?'Welcome Back':'Team Registration'}</span><h1>{initial.department.name}</h1><StatusBadge value={registrationStatus}/><p>{activeSection==='dashboard'?'Complete your squad registration and submit before the deadline.':'Review or update your registered department logo.'}</p></div><div className="team-identity-card"><button className="department-logo-button" type="button" onClick={()=>!locked&&logoInput.current?.click()} disabled={locked||!!busyAction} aria-label={locked?'Team logo editing is locked':'Replace team logo'}>{initial.logoUrl?<img src={initial.logoUrl} alt={`${initial.department.name} logo`}/>:<ImagePlus/>}{!locked&&<span><Camera size={13}/> Change</span>}</button><input ref={logoInput} className="visually-hidden" type="file" accept="image/png" onChange={updateTeamLogo}/><div><b>{initial.department.name}</b></div></div></div></header>}
  {initial.team.rejection_reason&&<div className="notice notice-error"><CircleAlert size={18}/><span><b>Team review:</b> {initial.team.rejection_reason}</span></div>}
  {notice&&<div className={`notice notice-${notice.type}`} role={notice.type==='error'?'alert':'status'}><span>{notice.text}</span><button type="button" onClick={()=>setNotice(null)} aria-label="Dismiss message"><X size={16}/></button></div>}
   {activeSection==='dashboard'&&<section className="mobile-overview" aria-label="Dashboard overview">
    <div className="mobile-overview-title"><h2>Dashboard Overview</h2><div className="dashboard-department-identity">{initial.logoUrl?<img src={initial.logoUrl} alt={`${initial.department.name} logo`}/>:<i>{initial.department.name.slice(0,2).toUpperCase()}</i>}<b>{initial.department.name}</b></div></div>
    <div className="mobile-stat-grid"><article><small>Total Players</small><b>{players.length}</b></article><article className="approved"><small>Approved</small><b>{approvedCount}</b></article><article className="pending"><small>Pending</small><b>{pendingCount}</b></article><article className="rejected"><small>Rejected</small><b>{rejectedCount}</b></article></div>
    <section className="mobile-dashboard-card position-card"><h3>Players by Position</h3><div className="position-card-content"><div className="position-pie" style={{background:`conic-gradient(${positionSegments.join(',')})`}} aria-label={`${players.length} players by position`}/><ul>{positionSummary.map(item=><li key={item.label}><i style={{background:item.color}}/><span>{item.label}</span><b>{item.count} ({players.length?Math.round(item.count/players.length*100):0}%)</b></li>)}</ul></div></section>
    <section className="mobile-dashboard-card mobile-registration-card"><h3>Registration Progress</h3><div><div className="mobile-progress-ring" style={{background:`conic-gradient(#079447 ${registrationPercent}%,#e3ebe6 ${registrationPercent}% 100%)`}}><span>{registrationPercent}%</span></div><strong>{players.length} / 25 Players</strong><dl><div><dt>Minimum:</dt><dd>20</dd></div><div><dt>Maximum:</dt><dd>25</dd></div></dl></div></section>
   </section>}
   {(activeSection==='add'||activeSection==='players')&&<div className={`department-workspace single-workspace ${activeSection}`} id="players">
    <section className="card add-player-card" id="add-player"><div className="section-title"><div><h2>Add player</h2></div><span>{players.length}/25</span></div>
    {locked?<div className="review-notice">Registration is submitted and editing is locked.</div>:players.length>=25?<div className="review-notice success-notice">Maximum squad size reached.</div>:<form className="player-form" onSubmit={addPlayer} noValidate>
     <div className="photo-upload-field"><label className={`photo-picker ${errors.photo?'has-error':''}`}>{photoPreview?<img src={photoPreview} alt="Selected player preview"/>:<><Camera size={34}/><b>Choose photo</b></>}<input name="photo" type="file" accept="image/jpeg,.jpg,.jpeg" onChange={e=>showPreview(e.target.files?.[0],setPhotoPreview)} required/></label><div><b>Player photo</b><p>JPEG only · Maximum 5 MB</p><p>Keep face centered, clear background.</p>{photoPreview&&<span className="replace-hint">Tap the preview to replace image</span>}<FieldError name="photo" errors={errors}/></div></div>
     <div className="player-form-grid">{playerFields()}</div><button className="btn primary-action full" disabled={!!busyAction}><Plus size={17}/>{busyAction==='add'?'Saving player...':'Save player'}</button>
    </form>}
   </section>
   <section className="card player-list-card players-screen-card"><div className="players-screen-heading"><h2>All Players</h2><b>{players.length} Players</b></div><div className="players-search-row"><label><Search/><input value={playerQuery} onChange={event=>setPlayerQuery(event.target.value)} placeholder="Search players..." aria-label="Search players"/></label><button type="button" aria-label="Player filters"><SlidersHorizontal/></button></div><div className="player-card-list">{visiblePlayers.length===0?<div className="empty-player-list"><Camera size={28}/><b>{players.length?'No players found':'No players registered yet'}</b><span>{players.length?'Try another search.':'Add the first player to begin building your squad.'}</span></div>:visiblePlayers.map(p=><article className="player-card" key={p.id}><img src={p.photo_url} alt={`${p.first_name} ${p.last_name}`}/><div className="player-card-info"><h3>{p.first_name} {p.last_name}</h3><p>{p.position==='Forward'?'Attacker':p.position}</p>{p.rejection_reason&&<div className="player-reason"><CircleAlert size={14}/> {p.rejection_reason}</div>}</div><b className="player-jersey">{String(p.jersey_number).padStart(2,'0')}</b>{!locked&&p.status!=='approved'&&<div className="player-actions"><button type="button" onClick={()=>{setErrors({});setEditing(p);}} aria-label={`Edit ${p.first_name} ${p.last_name}`}><Pencil/></button><button className="delete" type="button" onClick={()=>removePlayer(p.id)} disabled={busyAction===`remove-${p.id}`} aria-label={`Remove ${p.first_name} ${p.last_name}`}><Trash2/></button></div>}</article>)}</div></section>
  </div>}
  {activeSection==='review'&&<RegistrationReview department={initial.department.name} logoUrl={initial.logoUrl} players={players} submitted={locked} onSubmit={submitRegistration} busy={busyAction==='submit'}/>}
   {showSubmissionModal&&<div className="submission-success-backdrop" role="dialog" aria-modal="true" aria-labelledby="submission-success-title"><section className="submission-success-modal"><BrandLink/><div className="submission-success-art" aria-hidden="true"><i/><i/><i/><i/><i/><i/><ShieldCheck/></div><h2 id="submission-success-title">Registration Submitted!</h2><p>Your team registration has been submitted successfully. You will be notified once it has been reviewed.</p><button className="btn" type="button" onClick={()=>{setShowSubmissionModal(false);setActiveSection('dashboard')}}>Go to Dashboard</button><button className="submission-modal-logout" type="button" onClick={logout} disabled={!!busyAction}>Logout</button></section></div>}
    {!locked&&players.length<25&&activeSection==='players'&&<button className="mobile-add-player" type="button" onClick={()=>setActiveSection('add')}><Plus size={19}/> Add player</button>}
  {editing&&<div className="edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><form className="card edit-player-card" onSubmit={editPlayer} noValidate><div className="section-title"><div><div className="kicker">Update squad member</div><h2 id="edit-title">Edit player</h2></div><button type="button" className="icon-button" onClick={()=>setEditing(null)} aria-label="Close"><X size={20}/></button></div><input type="hidden" name="id" value={editing.id}/><div className="edit-photo-row"><img src={editPhotoPreview||editing.photo_url} alt={`${editing.first_name} ${editing.last_name}`}/><label className="btn secondary">Replace image<input name="photo" type="file" accept="image/jpeg,.jpg,.jpeg" onChange={e=>showPreview(e.target.files?.[0],setEditPhotoPreview,false)}/></label><span>JPEG only · Maximum 5 MB</span><FieldError name="photo" errors={errors}/></div><div className="player-form-grid">{playerFields(editing)}</div>{notice?.type==='error'&&<div className="notice notice-error">{notice.text}</div>}<div className="edit-actions"><button type="button" className="btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="btn" disabled={!!busyAction}>{busyAction==='edit'?'Saving changes...':'Save changes'}</button></div></form></div>}
   </div>
  </div>
 </main>;
}
